version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "127.0.0.1/test", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 10s
      timeout: 5s
      retries: 5

  parser:
    build:
      context: .
      dockerfile: service.dockerfile
    command: python -u main.py
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wb_parser_bot
    volumes:
      - ./logs:/app/logs

volumes:
  mongodb_data:
