version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  bot:
    build:
      context: .
      dockerfile: service.dockerfile
    command: python -u bot.py
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wb_parser_bot

  parser:
    build:
      context: .
      dockerfile: service.dockerfile
    command: python -u main.py
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wb_parser_bot

volumes:
  mongodb_data:
